# Generated by Django 4.1.6 on 2023-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.IntegerField(default=100),
        ),
    ]
